### ISSUE TITLE
meteor-collection2 schema crash Accounts.createUser()

### ISSUE THREAD

**Issue by yannissgarra** [aldeed/meteor-collection2#247]
I'm trying to use meteor-collection2 to validate my collection.

I have a service, on server side :

```
Meteor.methods
    UserSignUpService: (options) ->
        # create user
        Accounts.createUser options
```

That I call on client side :

```
Meteor.call 'UserSignUpService',
  email: 'my.email@domain.com'
  password: 'mypassword'
  profile:
    name: 'me'
```

And this is my schema :

```
# user profile
UserProfile = new SimpleSchema
  name:
    type: String
    min: 1
    max: 50
    optional: false

# user
User = new SimpleSchema
  emails:
    type: [Object]
    optional: false
  "emails.$.address":
    type: String
    regEx: SimpleSchema.RegEx.Email
  "emails.$.verified"
    type: Boolean
  createdAt:
    type: Date
  profile:
    type: UserProfile
    optional: false
  services:
    type: Object
    optional: true
    blackbox: true

# links to user collection
Meteor.users.attachSchema User
```

But, when user is created, there are not all fields in my mongo collection :

```
{ "_id" : "ikvBq95JBLXMCSnhT", "emails" : [ { "address" : "my.email@domain.com" } ] }
```

Whereas it should be :

```
{ "_id" : "WNkjGFhNkLpRR2Jex", "createdAt" : ISODate("2015-08-06T09:00:59.887Z"), "services" : { "password" : { "bcrypt" : "$2a$10$QvMLuI.Pv0bzzii3ZZP...fHfUlU9KiYfcsC2VHBf6q1OSPM6cfTW" }, "resume" : { "loginTokens" : [ { "when" : ISODate("2015-08-06T09:01:00.002Z"), "hashedToken" : "9KyqjRVSWm0nfIlS0sqODRmddlJ5GaG3mJ4+RMItOhk=" } ] } }, "emails" : [ { "address" : "my.email@domain.com", "verified" : false } ], "profile" : { "name" : "me" } }
```

Any idea on this problem ?
Many Thanks !
