### ISSUE TITLE
'is not an array' on update (upsert)

### ISSUE THREAD

**Issue by jiku** [aldeed/meteor-collection2#255]
While

```
Coll.upsert(selector, { $set: { data: [data] }})
```

with

```
CollSchema = new SimpleSchema
  data:
    type: [Object]
    label: 'Data'
    optional: true
    blackbox: true

Coll.attachSchema CollSchema
```

Works great on insert, adding data: [data] to the document where data is an Array with one element, 0, it fails on update, with this

```
Error: Data must be an array
```

I have tried

```
dataArray = []
dataArray.push data

Coll.upsert(selector, { $set: { data: dataArray }})
```

and made sure data is an array in all sorts of ways (_.isArray, instanceof, etc.)
Updates also work when not attaching the schema.
I don't want to manipulate [data] at all. Just replace it.
