### ISSUE TITLE
Question: Embedding a schema inline of another

### ISSUE THREAD

**Issue by vmatekole** [aldeed/meteor-collection2#296]
Hi!

I have the following schema:

```
unless @Schemas?
  @Schemas = {}

@Schemas.Common = new SimpleSchema
  modifiedBy:
    type: String
  modifiedAt:
    type: Date
  createdAt:
    type: Date
```
And wish to embed within another schema e.g.

```
@Schemas.UserCountry = new SimpleSchema
  name:
    type: String
  code:
    type: String
    regEx: /^[A-Z]{2}$/
  meta:
     type: @Schemas.Common
```
Is there a way to include the Common schemas inline and avoid referring to _meta_? So one can do data.updatedAt instead of data.meta.updatedAt? 

Thanks for your help!
